version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
    steps:
      - checkout
      - run:
          name: Package DKAN
          command: |
            mkdir /home/circleci/dkan
            mv /home/circleci/project/* /home/circleci/dkan
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/project
            dktl init
            ln -s ../dkan dkan
            dktl make
            dktl drush site-install -y --notify
            ls -lha
      - run:
          name: Run tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl test:behat



